# Generated by Django 5.1.1 on 2024-09-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_rafaburguer", "0002_produtocadastromodel_preço"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtocadastromodel",
            old_name="Preço",
            new_name="preço",
        ),
    ]
